import { StockMarketSymbols } from './types';

export const mockStockMarketSymbols = {
  AAPL: { name: 'Apple Inc.', sector: 'Tech' },
  ABBN: { name: 'ABB Ltd', sector: 'Electrical equipment' },
  ACHI: { name: 'Achiko', sector: 'Biotechnology' },
  ADBE: { name: 'Adobe Systems Inc.', sector: 'Tech' },
  ADEN: { name: 'Adecco Group', sector: 'Professional Services' },
  ADVN: { name: 'Adval Tech Holding', sector: 'Industrial Machinery' },
  ADXN: { name: 'Addex Pharmaceuticals', sector: 'Pharmaceuticals' },
  AEVS: { name: 'Aevis Victoria', sector: 'Real Estate' },
  AFP: { name: 'Aluflexpack', sector: 'Packaging' },
  AIR: { name: 'Airbus SE', sector: 'Aerospace' },
  AIRE: { name: 'Airesis', sector: 'Healthcare Technology' },
  ALC: { name: 'Alcon Inc', sector: 'Pharmaceuticals' },
  ALLN: { name: 'Allreal Holding', sector: 'Real Estate' },
  ALSN: { name: 'ALSO Holding', sector: 'Technology Distribution' },
  ALV: { name: 'Allianz SE', sector: 'Financial Services' },
  AMD: { name: 'AMD Inc.', sector: 'Semiconductors' },
  AMRZ: { name: 'Amaris Group', sector: 'Consulting' },
  AMS: { name: 'ams Osram', sector: 'Semiconductors' },
  AMZN: { name: 'Amazon.com Inc.', sector: 'Tech' },
  APGN: { name: 'APG SGA AG', sector: 'Advertising & Media' },
  ARBN: { name: 'Arbonia', sector: 'Building Materials' },
  ARON: { name: 'Arundel', sector: 'Consumer Services' },
  ARYN: { name: 'Aryzta', sector: 'Food & Beverages' },
  ASCN: { name: 'Ascom', sector: 'Telecommunications Equipment' },
  ASWN: { name: 'ASmallWorld', sector: 'Social Media' },
  AUTN: { name: 'Autoneum', sector: 'Automotive Components' },
  AVOL: { name: 'Avolta', sector: 'Travel Retail' },
  BA: { name: 'BAE Systems plc', sector: 'Defense' },
  BAER: { name: 'Julius Baer', sector: 'Financial Services' },
  BALN: { name: 'Baloise', sector: 'Insurance' },
  BANB: { name: 'Bachem Holding', sector: 'Biochemicals' },
  BARN: { name: 'Barry Callebaut', sector: 'Chocolate' },
  BBN: { name: 'Bellevue Group', sector: 'Investment Management' },
  BBY: { name: 'Balfour Beatty plc', sector: 'Construction' },
  BCGE: { name: 'Banque Cantonale de Genève', sector: 'Financial Services' },
  BCHN: { name: 'Burckhardt Compression', sector: 'Compression Technology' },
  BCJ: { name: 'Banque Cantonale du Jura', sector: 'Financial Services' },
  BCVN: { name: 'Banque Cantonale Vaudoise', sector: 'Financial Services' },
  BEAM: { name: 'Belimo', sector: 'HVAC' },
  BEAN: { name: 'Belimo Holding', sector: 'HVAC Systems' },
  BEKN: { name: 'Berner Kantonalbank', sector: 'Financial Services' },
  BELL: { name: 'Bell Food Group', sector: 'Food & Beverages' },
  BION: { name: 'BB Biotech', sector: 'Biotechnology Investment' },
  BKW: { name: 'BKW Energie', sector: 'Energy' },
  BKWB: { name: 'BKW Energie', sector: 'Electrical Power' },
  BLKB: { name: 'Basellandschaftliche Kantonalbank', sector: 'Financial Services' },
  BLS: { name: 'Blackstone Resources AG', sector: 'Mining' },
  BMWYY: { name: 'BMW AG', sector: 'Automotive' },
  BNNN: { name: 'Danone S.A.', sector: 'Food & Beverages' },
  BNP: { name: 'BNP Paribas', sector: 'Financial Services' },
  BO: { name: 'Blue Origin', sector: 'Aerospace' },
  BOBNN: { name: 'Bobst Group', sector: 'Packaging Machinery' },
  BOSN: { name: 'Bossard Holding', sector: 'Fastening Technology' },
  BPDG: { name: 'Banque Profil de Gestion', sector: 'Financial Services' },
  BRKN: { name: 'Burkhalter Holding', sector: 'Electrical Engineering' },
  BSKP: { name: 'Basler Kantonalbank', sector: 'Financial Services' },
  BSLN: { name: 'Basilea Pharmaceutica', sector: 'Pharmaceuticals' },
  BUCN: { name: 'Bucher Industries', sector: 'Industrial Equipment' },
  BVZN: { name: 'BVZ Holding', sector: 'Transportation' },
  CALN: { name: 'Calida', sector: 'Apparel' },
  CARL: { name: 'Carlsberg Group', sector: 'Food & Beverages' },
  CFR: { name: 'Compagnie Financière Richemont SA', sector: 'Luxury Goods' },
  CFT: { name: 'Compagnie financière Tradition', sector: 'Financial Services' },
  CICN: { name: 'Cicor Technologies', sector: 'Electronics Manufacturing' },
  CIE: { name: 'CI Com', sector: 'Telecommunications' },
  CLC: { name: 'Colgate-Palmolive Co.', sector: 'Consumer Goods' },
  CLN: { name: 'Clariant', sector: 'Chemicals' },
  CLTN: { name: 'Coltene Holding', sector: 'Dental Products' },
  CLXN: { name: 'Crealogix Holding', sector: 'Financial Technology' },
  CMBN: { name: 'Cembra Money Bank', sector: 'Financial Services' },
  CON: { name: 'Conzzeta AG', sector: 'Diversified Industries' },
  COOP: { name: 'Coop Group', sector: 'Food & Beverages' },
  COPN: { name: 'Cosmo Pharmaceuticals', sector: 'Pharmaceuticals' },
  COTN: { name: 'Comet Holding', sector: 'Industrial Equipment' },
  CPHN: { name: 'CPH Chemie + Papier', sector: 'Chemicals & Paper' },
  CRH: { name: 'CRH plc', sector: 'Construction' },
  CRM: { name: 'Salesforce Inc.', sector: 'Tech' },
  CS: { name: 'AXA Group', sector: 'Financial Services' },
  CSGN: { name: 'Credit Suisse', sector: 'Financial Services' },
  DAE: { name: 'Dätwyler Holding', sector: 'Industrial Components' },
  DB1: { name: 'Deutsche Börse AG', sector: 'Equity' },
  DB: { name: 'Deutsche Bank AG', sector: 'Financial Services' },
  DG: { name: 'Vinci SA', sector: 'Construction' },
  DKSH: { name: 'DKSH', sector: 'Market Expansion Services' },
  DOKA: { name: 'Dormakaba', sector: 'Security Solutions' },
  DUFN: { name: 'Dufry', sector: 'Travel Retail' },
  EFGN: { name: 'EFG International', sector: 'Wealth Management' },
  ELMN: { name: 'Elma Electronic', sector: 'Electronics' },
  EMMI: { name: 'Emmi AG', sector: 'Food & Beverages' },
  EMMN: { name: 'Emmi', sector: 'Dairy Products' },
  EMSN: { name: 'Ems-Chemie', sector: 'Chemicals' },
  ENX: { name: 'Euronext N.V.', sector: 'Equity' },
  ESUN: { name: 'Edisun Power', sector: 'Renewable Energy' },
  EVE: { name: 'Evolva', sector: 'Biotechnology' },
  FHZN: { name: 'Flughafen Zürich', sector: 'Airport operator' },
  FI: { name: 'Georg Fischer', sector: 'Manufacturing' },
  FMC: { name: 'Ford Motor Co.', sector: 'Automotive' },
  FORN: { name: 'Forbo Holding', sector: 'Flooring Solutions' },
  FREN: { name: 'Fundamenta Real Estate AG', sector: 'Real Estate' },
  FTON: { name: 'Feintool International Holding', sector: 'Industrial Machinery' },
  GALD: { name: 'Galderma S.A.', sector: 'Medical Devices' },
  GALE: { name: 'Galenica', sector: 'Pharmaceuticals' },
  GAM: { name: 'GAM', sector: 'Asset Management' },
  GAV: { name: 'Carlo Gavazzi Holding', sector: 'Automation' },
  GEBN: { name: 'Geberit AG', sector: 'Sanitary engineering' },
  GF: { name: 'Georg Fischer', sector: 'Manufacturing' },
  GIVN: { name: 'Givaudan SA', sector: 'Chemistry' },
  GLEN: { name: 'Glencore plc', sector: 'Commodities' },
  GLKBN: { name: 'Glarner Kantonalbank', sector: 'Financial Services' },
  GMC: { name: 'General Motors Co.', sector: 'Automotive' },
  GMI: { name: 'Groupe Minoteries', sector: 'Food & Beverages' },
  GOOGL: { name: 'Google Inc.', sector: 'Tech' },
  GRKP: { name: 'Graubündner Kantonalbank', sector: 'Financial Services' },
  GUR: { name: 'Gurit Holding', sector: 'Composite Materials' },
  HBLN: { name: 'Hypothekarbank Lenzburg', sector: 'Financial Services' },
  HEIA: { name: 'Heineken N.V.', sector: 'Food & Beverages' },
  HELN: { name: 'Helvetia', sector: 'Insurance' },
  HIAG: { name: 'HIAG Immobilien', sector: 'Real Estate' },
  HLEE: { name: 'Highlight Event and Entertainment', sector: 'Entertainment' },
  HO: { name: 'Thales Group', sector: 'Defense' },
  HOCN: { name: 'Hochdorf Holding', sector: 'Food Processing' },
  HOLN: { name: 'Holcim Limited', sector: 'Building materials' },
  HREN: { name: 'Romande Energie Holding', sector: 'Energy' },
  HUBN: { name: 'Huber+Suhner', sector: 'Telecommunications' },
  HYMTF: { name: 'Hyundai Motor Co.', sector: 'Automotive' },
  IDIA: { name: 'Idorsia', sector: 'Pharmaceuticals' },
  IFCN: { name: 'Inficon', sector: 'Measurement Technology' },
  IMPN: { name: 'Implenia', sector: 'Construction' },
  INA: { name: 'Ina Invest', sector: 'Real Estate Development' },
  INRN: { name: 'Interroll Holding', sector: 'Material Handling' },
  INTC: { name: 'Intel Corp.', sector: 'Tech' },
  IREN: { name: 'Investis', sector: 'Real Estate' },
  ISN: { name: 'Intershop Holding', sector: 'Real Estate' },
  JFN: { name: 'Jungfraubahn', sector: 'Transportation' },
  JNJ: { name: 'Johnson & Johnson', sector: 'Pharmaceuticals' },
  KARN: { name: 'Kardex Group', sector: 'Logistics Solutions' },
  KHC: { name: 'Kraft Heinz Co.', sector: 'Food & Beverages' },
  KIAG: { name: 'Kia Corp.', sector: 'Automotive' },
  KLIN: { name: 'Klingelnberg', sector: 'Gear Technology' },
  KNIN: { name: 'Kuehne + Nagel', sector: 'Logistics' },
  KO: { name: 'Coca-Cola Co.', sector: 'Food & Beverages' },
  KOMN: { name: 'Komax Holding', sector: 'Automation' },
  KUD: { name: 'Kudelski', sector: 'Digital Security' },
  KURN: { name: 'Kuros Biosciences', sector: 'Biotechnology' },
  LAND: { name: 'Landis+Gyr', sector: 'Energy Management' },
  LDO: { name: 'Leonardo S.p.A.', sector: 'Defense' },
  LECN: { name: 'Leclanché', sector: 'Energy Storage' },
  LEHN: { name: 'Lem Holding', sector: 'Electronics' },
  LEON: { name: 'Leonteq', sector: 'Financial Technology' },
  LINN: { name: 'Bank Linth LLB', sector: 'Financial Services' },
  LINTH: { name: 'Linth AG', sector: 'Food & Beverages' },
  LISN: { name: 'Lindt & Sprüngli (2 share lines)', sector: 'Confectionery' },
  LISP: { name: 'Lindt & Sprüngli', sector: 'Confectionery' },
  LLBN: { name: 'Liechtensteinische Landesbank', sector: 'Financial Services' },
  LLQ: { name: 'Lalique Group', sector: 'Luxury Goods' },
  LMB: { name: 'Lamborghini S.p.A.', sector: 'Automotive' },
  LMN: { name: 'lastminute.com', sector: 'Travel Services' },
  LMT: { name: 'Lockheed Martin Corp.', sector: 'Aerospace' },
  LOGN: { name: 'Logitech International SA', sector: 'Computer hardware and software' },
  LONN: { name: 'Lonza Group AG', sector: 'Chemistry' },
  LSEG: { name: 'London Stock Exchange Group', sector: 'Equity' },
  LUKN: { name: 'Luzerner Kantonalbank', sector: 'Financial Services' },
  MBTN: { name: 'Meyer Burger', sector: 'Photovoltaics' },
  MCHN: { name: 'MCH Group', sector: 'Event Management' },
  MED: { name: 'Medartis', sector: 'Medical Technology' },
  META: { name: 'Facebook Inc.', sector: 'Tech' },
  METN: { name: 'Metall Zug', sector: 'Industrial Equipment' },
  MIG: { name: 'Migros', sector: 'Food & Beverages' },
  MIKN: { name: 'Mikron Holding', sector: 'Precision Machinery' },
  MOBN: { name: 'Mobimo Holding', sector: 'Real Estate' },
  MOLN: { name: 'Molecular Partners', sector: 'Biotechnology' },
  MOVE: { name: 'Medacta Group', sector: 'Medical Devices' },
  MOZN: { name: 'Mobilezone', sector: 'Telecommunications' },
  MRNA: { name: 'Moderna Inc.', sector: 'Pharmaceuticals' },
  MSFT: { name: 'Microsoft Corp.', sector: 'Tech' },
  MTG: { name: 'Meier Tobler', sector: 'HVAC Systems' },
  NESN: { name: 'Nestlé SA', sector: 'Food & Beverages' },
  NFLX: { name: 'Netflix Inc.', sector: 'Tech' },
  NOVN: { name: 'Novartis International AG', sector: 'Pharmaceuticals' },
  NPRO: { name: 'Nestlé Professional', sector: 'Food & Beverages' },
  NREN: { name: 'Novavest Real Estate', sector: 'Real Estate' },
  NSRGY: { name: 'Nestlé S.A.', sector: 'Food & Beverages' },
  NVDA: { name: 'NVIDIA Corp.', sector: 'Tech' },
  NVS: { name: 'Novartis AG', sector: 'Pharmaceuticals' },
  NW: { name: 'Nestlé Waters', sector: 'Food & Beverages' },
  NWRN: { name: 'Newron Pharmaceuticals', sector: 'Pharmaceuticals' },
  OBSN: { name: 'ObsEva SA', sector: 'Biotechnology' },
  ODHN: { name: 'Orascom Development Holding', sector: 'Hospitality' },
  OERL: { name: 'OC Oerlikon', sector: 'Textile Machinery' },
  OFN: { name: 'Orell Füssli', sector: 'Publishing' },
  ORCL: { name: 'Oracle Corp.', sector: 'Tech' },
  ORON: { name: 'Orior', sector: 'Food & Beverages' },
  P911: { name: 'Porsche AG', sector: 'Automotive' },
  PEAN: { name: 'Peach Property', sector: 'Real Estate' },
  PEDU: { name: 'Perrot Duval Holding', sector: 'Automation' },
  PEHN: { name: 'Private Equity Holding', sector: 'Investment Management' },
  PEP: { name: 'PepsiCo Inc.', sector: 'Food & Beverages' },
  PFE: { name: 'Pfizer Inc.', sector: 'Pharmaceuticals' },
  PGC: { name: 'Procter & Gamble Co.', sector: 'Consumer Goods' },
  PGHN: { name: 'Partners Group Holding AG', sector: 'Private equity' },
  PLAN: { name: 'Plazza', sector: 'Real Estate' },
  PM: { name: 'Phoenix Mecano', sector: 'Industrial Components' },
  PMAG: { name: 'Pierer Mobility', sector: 'Motorcycles' },
  PNHO: { name: 'Poenina Holding', sector: 'Construction' },
  POLN: { name: 'Polyphor', sector: 'Pharmaceuticals' },
  PRFN: { name: 'Perfect Holding', sector: 'Aviation Services' },
  PSPN: { name: 'PSP Swiss Property', sector: 'Real Estate' },
  PW: { name: 'Pratt & Whitney', sector: 'Aerospace' },
  PYPL: { name: 'PayPal Holdings Inc.', sector: 'Financial Services' },
  RACE: { name: 'Ferrari N.V.', sector: 'Automotive' },
  RIEN: { name: 'Rieter', sector: 'Textile Machinery' },
  RIV: { name: 'Rivella SA', sector: 'Food & Beverages' },
  RLF: { name: 'Relief Therapeutics', sector: 'Pharmaceuticals' },
  ROG: { name: 'Roche Holding AG (2 share lines)', sector: 'Pharmaceuticals' },
  ROL: { name: 'Von Roll Holding AG', sector: 'Industrial Manufacturing' },
  ROSE: { name: 'Zur Rose Group', sector: 'Healthcare Services' },
  RRH: { name: 'Rolls-Royce Holdings plc', sector: 'Aerospace' },
  SAHN: { name: 'Schaffner Holding', sector: 'Electrical Engineering' },
  SANN: { name: 'Santhera Pharmaceuticals Holding', sector: 'Pharmaceuticals' },
  SAP: { name: 'SAP SE', sector: 'Tech' },
  SCHN: { name: 'Schindler (2 share lines)', sector: 'Vertical transportation' },
  SCHP: { name: 'Schindler Holding', sector: 'Elevators and Escalators' },
  SCMN: { name: 'Swisscom AG', sector: 'Telecommunications' },
  SDZ: { name: 'Sandoz', sector: 'Pharmaceuticals' },
  SENS: { name: 'Sensirion Holding', sector: 'Sensor Technology' },
  SFPN: { name: 'SF Urban Properties', sector: 'Real Estate' },
  SFSN: { name: 'SFS Group', sector: 'Precision Components' },
  SFZN: { name: 'Siegfried Holding', sector: 'Pharmaceuticals' },
  SGKN: { name: 'St.Galler Kantonalbank', sector: 'Financial Services' },
  SGSN: { name: 'SGS AG', sector: 'Quality' },
  SHOP: { name: 'Shopify Inc.', sector: 'Tech' },
  SIGN: { name: 'SIG Group', sector: 'Packaging' },
  SIKA: { name: 'Sika AG', sector: 'Chemistry' },
  SKIN: { name: 'Cassiopea', sector: 'Pharmaceuticals' },
  SLHN: { name: 'Swiss Life Holding AG', sector: 'Insurance' },
  SNBN: { name: 'Schweizerische Nationalbank', sector: 'Central Financial Services' },
  SOON: { name: 'Sonova', sector: 'Medical devices' },
  SPCE: { name: 'Spice Private Equity', sector: 'Private Equity' },
  SPOT: { name: 'Spotify Technology S.A.', sector: 'Tech' },
  SPSN: { name: 'Swiss Prime Site', sector: 'Real Estate' },
  SPX: { name: 'SpaceX', sector: 'Aerospace' },
  SQ: { name: 'Square Inc.', sector: 'Financial Services' },
  SRAIL: { name: 'Stadler Rail', sector: 'Railway Vehicles' },
  SREN: { name: 'Swiss Reinsurance Company Ltd', sector: 'Insurance' },
  STGN: { name: 'Starrag Group', sector: 'Machine Tools' },
  STLN: { name: 'Swiss Steel Group', sector: 'Steel Production' },
  STMN: { name: 'Straumann', sector: 'Pharmaceuticals' },
  STRN: { name: 'Schlatter Holding', sector: 'Welding Technology' },
  SUN: { name: 'Sulzer AG', sector: 'Industrial Engineering' },
  SWON: { name: 'SoftwareONE', sector: 'Software Solutions' },
  SWTQ: { name: 'Schweiter Technologies', sector: 'Composite Materials' },
  TECN: { name: 'Tecan', sector: 'Laboratory' },
  TEMN: { name: 'Temenos', sector: 'Software' },
  TIBN: { name: 'Titlis Bergbahnen', sector: 'Tourism' },
  TKBP: { name: 'Thurgauer Kantonalbank', sector: 'Financial Services' },
  TMC: { name: 'Toyota Motor Corp.', sector: 'Automotive' },
  TOHN: { name: 'Tornos Holding', sector: 'Machine Tools' },
  TSLA: { name: 'Tesla Inc.', sector: 'Automotive' },
  TWTR: { name: 'Twitter Inc.', sector: 'Tech' },
  TXGN: { name: 'TX Group', sector: 'Media' },
  UBS: { name: 'UBS Group AG', sector: 'Financial Services' },
  UBSG: { name: 'UBS Group AG', sector: 'Financial Services' },
  UBXN: { name: 'U-blox', sector: 'Semiconductors' },
  UHR: { name: 'Swatch Group', sector: 'Luxury Goods' },
  UHRN: { name: 'Swatch Group', sector: 'Luxury Goods' },
  ULP: { name: 'Unilever plc', sector: 'Food & Beverages' },
  VACN: { name: 'VAT Group', sector: 'Vacuum technology' },
  VAHN: { name: 'Vaudoise Assurances', sector: 'Insurance' },
  VALN: { name: 'Valora', sector: 'Retail' },
  VARN: { name: 'Varia US Properties', sector: 'Real Estate' },
  VATN: { name: 'Valiant Holding', sector: 'Financial Services' },
  VBSN: { name: 'IVF Hartmann Holding', sector: 'Medical Supplies' },
  VET: { name: 'Vetropack Holding', sector: 'Packaging & Materials' },
  VGGA: { name: 'Virgin Galactic', sector: 'Aerospace' },
  VIFN: { name: 'Vifor Pharma', sector: 'Pharmaceuticals' },
  VILN: { name: 'Villars Holding', sector: 'Food & Beverage' },
  VLRT: { name: 'Valartis Group', sector: 'Financial Services' },
  VONN: { name: 'Vontobel', sector: 'Financial Services' },
  VPBN: { name: 'VP Bank', sector: 'Financial Services' },
  VWAGY: { name: 'Volkswagen AG', sector: 'Automotive' },
  VZN: { name: 'VZ Holding', sector: 'Financial Services' },
  VZUG: { name: 'V-Zug', sector: 'Household Appliances' },
  WARN: { name: 'Warteck Invest', sector: 'Real Estate' },
  WIHN: { name: 'WISeKey', sector: 'Technology' },
  WKB: { name: 'Walliser Kantonalbank', sector: 'Financial Services' },
  YPSN: { name: 'Ypsomed Holding', sector: 'Medical Devices' },
  ZEHN: { name: 'Zehnder Group', sector: 'Building Technology' },
  ZG: { name: 'Zuger Kantonalbank', sector: 'Financial Services' },
  ZMC: { name: 'Zoom Video Communications', sector: 'Tech' },
  ZUBN: { name: 'Züblin Immobilien Holding', sector: 'Real Estate' },
  ZUGN: { name: 'Zug Estates', sector: 'Real Estate' },
  ZURN: { name: 'Zurich Insurance Group AG', sector: 'Insurance' },
  ZWN: { name: 'Zwahlen et Mayr', sector: 'Food & Beverage' },
} satisfies StockMarketSymbols;
